"""
5G Network Anomaly Detector - Python Analysis Layer
Reads alerts.json generated by the C++ engine and produces visualizations.
"""

import json
import os
from datetime import datetime
from collections import Counter
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


def load_alerts(filepath: str = "alerts.json") -> list[dict]:
    """Load alerts exported by the C++ engine."""
    if not os.path.exists(filepath):
        print(f"[WARNING] {filepath} not found. Using sample data.")
        return generate_sample_data()

    with open(filepath, "r") as f:
        return json.load(f)


def generate_sample_data() -> list[dict]:
    """Generate sample data for demo when C++ output is unavailable."""
    return [
        {"timestamp": "2025-02-17 10:00:01", "level": "HIGH",
         "message": "High latency: 250ms", "source_ip": "192.168.1.10", "severity": 0.7},
        {"timestamp": "2025-02-17 10:00:05", "level": "CRITICAL",
         "message": "Flood attack", "source_ip": "10.10.10.10", "severity": 0.95},
        {"timestamp": "2025-02-17 10:00:10", "level": "MEDIUM",
         "message": "High latency: 150ms", "source_ip": "192.168.1.20", "severity": 0.45},
        {"timestamp": "2025-02-17 10:00:15", "level": "LOW",
         "message": "Unknown protocol", "source_ip": "192.168.1.30", "severity": 0.2},
        {"timestamp": "2025-02-17 10:00:20", "level": "CRITICAL",
         "message": "Flood attack", "source_ip": "10.10.10.10", "severity": 0.98},
        {"timestamp": "2025-02-17 10:00:25", "level": "HIGH",
         "message": "High latency: 300ms", "source_ip": "192.168.1.40", "severity": 0.75},
        {"timestamp": "2025-02-17 10:00:30", "level": "MEDIUM",
         "message": "Packet loss detected", "source_ip": "192.168.1.50", "severity": 0.5},
    ]


def analyze(alerts: list[dict]) -> dict:
    """Compute summary statistics from alerts."""
    if not alerts:
        return {}

    level_counts  = Counter(a["level"] for a in alerts)
    ip_counts     = Counter(a["source_ip"] for a in alerts)
    severities    = [a["severity"] for a in alerts]
    top_offenders = ip_counts.most_common(5)

    return {
        "total":         len(alerts),
        "level_counts":  dict(level_counts),
        "avg_severity":  sum(severities) / len(severities),
        "max_severity":  max(severities),
        "top_offenders": top_offenders,
    }


def visualize(alerts: list[dict], stats: dict, output_dir: str = ".") -> None:
    """Generate dashboard with 3 plots."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle("5G Network Anomaly Detection Dashboard", fontsize=16, fontweight="bold")

    colors = {
        "CRITICAL": "#d32f2f",
        "HIGH":     "#f57c00",
        "MEDIUM":   "#fbc02d",
        "LOW":      "#388e3c",
    }

    # ── Plot 1: Alert levels distribution ──────────────────────────
    ax1 = axes[0]
    levels = list(stats["level_counts"].keys())
    counts = list(stats["level_counts"].values())
    bar_colors = [colors.get(l, "#888") for l in levels]
    bars = ax1.bar(levels, counts, color=bar_colors, edgecolor="white", linewidth=1.5)
    ax1.set_title("Alerts by Severity Level", fontweight="bold")
    ax1.set_xlabel("Level")
    ax1.set_ylabel("Count")
    for bar, count in zip(bars, counts):
        ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.05,
                 str(count), ha="center", va="bottom", fontweight="bold")
    ax1.set_ylim(0, max(counts) * 1.3)

    # ── Plot 2: Severity over time ──────────────────────────────────
    ax2 = axes[1]
    times = list(range(len(alerts)))
    severities = [a["severity"] for a in alerts]
    point_colors = [colors.get(a["level"], "#888") for a in alerts]
    ax2.plot(times, severities, color="#1565c0", linewidth=1.5, alpha=0.5, zorder=1)
    ax2.scatter(times, severities, c=point_colors, s=80, zorder=2, edgecolors="white")
    ax2.axhline(y=0.8, color="#d32f2f", linestyle="--", alpha=0.7, label="Critical threshold")
    ax2.axhline(y=0.6, color="#f57c00", linestyle="--", alpha=0.7, label="High threshold")
    ax2.set_title("Severity Over Time", fontweight="bold")
    ax2.set_xlabel("Alert Index")
    ax2.set_ylabel("Severity (0-1)")
    ax2.set_ylim(0, 1.1)
    ax2.legend(fontsize=8)
    patches = [mpatches.Patch(color=v, label=k) for k, v in colors.items()]
    ax2.legend(handles=patches, fontsize=7, loc="upper left")

    # ── Plot 3: Top offending IPs ───────────────────────────────────
    ax3 = axes[2]
    if stats["top_offenders"]:
        ips, ip_counts = zip(*stats["top_offenders"])
        ax3.barh(ips, ip_counts, color="#1565c0", edgecolor="white")
        ax3.set_title("Top Offending IPs", fontweight="bold")
        ax3.set_xlabel("Alert Count")
        ax3.set_ylabel("Source IP")
        for i, (ip, count) in enumerate(zip(ips, ip_counts)):
            ax3.text(count + 0.05, i, str(count), va="center", fontweight="bold")

    plt.tight_layout()
    out_path = os.path.join(output_dir, "anomaly_dashboard.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"[✓] Dashboard saved to {out_path}")
    plt.show()


def print_report(stats: dict) -> None:
    """Print summary report to console."""
    print("\n" + "=" * 50)
    print("       5G ANOMALY DETECTION REPORT")
    print("=" * 50)
    print(f"Total Alerts     : {stats['total']}")
    print(f"Average Severity : {stats['avg_severity']:.2f}")
    print(f"Max Severity     : {stats['max_severity']:.2f}")
    print("\nAlerts by Level:")
    for level, count in stats["level_counts"].items():
        print(f"  {level:<10}: {count}")
    print("\nTop Offending IPs:")
    for ip, count in stats["top_offenders"]:
        print(f"  {ip:<20}: {count} alert(s)")
    print("=" * 50)


if __name__ == "__main__":
    alerts = load_alerts("alerts.json")
    stats  = analyze(alerts)
    print_report(stats)
    visualize(alerts, stats)
